2024-02-23 09:26:42.6724 | [6] | ERROR | FuctionName=BaseDal | Error=System.Data.SqlClient.SqlException (0x80131904): 已超過連接逾時的設定。在嘗試使用登入前的信號交換確認時超過逾時等待的時間。這可能是登入前的信號交換發生失敗,或伺服器無法及時回應所造成。  嘗試連接到這部伺服器所花費的時間為 - [登入前] 初始設定=20592; 信號交換=43;  ---> System.ComponentModel.Win32Exception (0x80004005): 等候操作已逾時。   於 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)   於 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)   於 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)   於 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)   於 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)   於 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)   於 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)   於 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)   於 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)   於 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)   於 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)   於 System.Data.SqlClient.SqlConnection.Open()   於 FTC_MES_MVC.Models.dalBase..ctor() 於 C:\Users\N000191304\Documents\方\開發環境\personLocation-master\personlocation\FTC_MVC_Template\Models\dalBase.cs: 行 37ClientConnectionId:0db6bc58-9026-4649-91aa-45282950c8e8Error Number:-2,State:0,Class:11
2024-02-23 09:26:45.2411 | [6] | ERROR | FuctionName=getMesApHostDb | Error=System.Data.SqlClient.SqlException (0x80131904): 已超過連接逾時的設定。在嘗試使用登入前的信號交換確認時超過逾時等待的時間。這可能是登入前的信號交換發生失敗,或伺服器無法及時回應所造成。  嘗試連接到這部伺服器所花費的時間為 - [登入前] 初始設定=20592; 信號交換=43;  ---> System.ComponentModel.Win32Exception (0x80004005): 等候操作已逾時。   於 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)   於 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)   於 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)   於 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)   於 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)   於 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)   於 System.Data.SqlClient.SqlConnection.Open()   於 Dapper.SqlMapper.<QueryImpl>d__138`1.MoveNext()   於 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)   於 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)   於 Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)   於 FTC_MES_MVC.Models.Services.dalCommService.getMesApHostDb() 於 C:\Users\N000191304\Documents\方\開發環境\personLocation-master\personlocation\FTC_MVC_Template\Models\UserManage\Dals\dalCommService.cs: 行 27ClientConnectionId:0db6bc58-9026-4649-91aa-45282950c8e8Error Number:-2,State:0,Class:11
2024-02-23 09:26:45.4998 | [6] | ERROR | FuctionName=Account.Login | Error=System.Data.SqlClient.SqlException (0x80131904): 已超過連接逾時的設定。在嘗試使用登入前的信號交換確認時超過逾時等待的時間。這可能是登入前的信號交換發生失敗,或伺服器無法及時回應所造成。  嘗試連接到這部伺服器所花費的時間為 - [登入前] 初始設定=20592; 信號交換=43;  ---> System.ComponentModel.Win32Exception (0x80004005): 等候操作已逾時。   於 FTC_MES_MVC.Models.Services.dalCommService.getMesApHostDb() 於 C:\Users\N000191304\Documents\方\開發環境\personLocation-master\personlocation\FTC_MVC_Template\Models\UserManage\Dals\dalCommService.cs: 行 32   於 FTC_MES_MVC.Controllers.AccountController.Login(String returnUrl, String status) 於 C:\Users\N000191304\Documents\方\開發環境\personLocation-master\personlocation\FTC_MVC_Template\Controllers\UserManage\AccountController.cs: 行 50ClientConnectionId:0db6bc58-9026-4649-91aa-45282950c8e8Error Number:-2,State:0,Class:11
